### ISSUE TITLE
Intl.DisplayNames MDN documentation

### ISSUE THREAD

**Issue by romulocintra** [tc39/ecma402-mdn#1]
Create Documentation for **Intl.DisplayNames** 

- [x] Review Readme documentation and examples
- [x] Create [MDN Main Docs Page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DisplayNames) 

**MDN Pages :**
- [x] main page basic structure
- [ ] prototype
- [ ] of
- [ ] options

**Examples MDN :** 
- [x] Static examples of usage
- [X] Interactive  examples of usage

 **Browser compat-data :** 
- [x] Browser compat
- [x] Embed Test 262 page

**Comment by romulocintra** [comment]
This is feature is landing on Chrome 81 this week. Page still in draft we should start improving this one, i added some basic look and feel.

**Comment by meyerweb** [comment]
I just did a survey of the MDN documentation and it looks like the outstanding to-dos on this issue are done, with one method apparently having a new name.  Agreed and ready to close, or is more needed on MDN?
