### ISSUE TITLE
Include more detailed information about options bag

### ISSUE THREAD

**Issue by littledan** [tc39/ecma402-mdn#10]
From what's written now, e.g., under parameters at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat , I'd feel a little uncomfortable using Intl.DateTimeFormat. It'd be good to have examples for each option, for example, and maybe a little more explanation of what it does.

**Comment by romulocintra** [comment]
Hi @littledan  i think this was addressed on  #6  i see a better structured documentation format compared with previous ones and other languages. I saw this improved in other Intl pages. If you are ok we can close this one
