### ISSUE TITLE
Finish documenting Unified NumberFormat proposal

### ISSUE THREAD

**Issue by sffc** [tc39/ecma402-mdn#12]
Original issue: https://github.com/tc39/proposal-unified-intl-numberformat/issues/50

- [x] Review Readme documentation and examples

[Intl.NumberFormat MDN page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat) 

**Parameters doc MDN :** 
- [x] `style`, `unit` and `unitDisplay` examples 
- [x] `notation` and  `compactDisplay`
- [x] `signDisplay` and  `currencySign`

**Static Examples MDN :** 
- [x] `style`, `unit` and `unitDisplay` examples 
- [x] `notation` and  `compactDisplay`
- [x] `signDisplay` and  `currencySign`

**Interactive Examples MDN :** 
- [ ] `style`, `unit` and `unitDisplay` examples 
- [ ] `notation` and  `compactDisplay`
- [ ] `signDisplay` and  `currencySign`

 **Browser compat-data :** 
- [x] unified numberformat

**Comment by Elchi3** [comment]
Browser compat data: https://github.com/mdn/browser-compat-data/pull/6299
Examples: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat#Examples

Let me know if anyone has any feedback.

**Comment by romulocintra** [comment]
Closing this one due tc39/proposal-unified-intl-numberformat#50 is closed, still missing interactive examples but already have a set of valuable examples there
