### ISSUE TITLE
Document @@toStringTag values, or decide not to document them

### ISSUE THREAD

**Issue by sffc** [tc39/ecma402-mdn#15]
https://github.com/tc39/ecma402/pull/430 and https://github.com/tc39/ecma402/pull/487 define new `@@toStringTag` values for ECMA-402 types.  We may or may not need to document these in MDN.  Check for precedent in documenting these values, and then either update MDN or close this issue.

**Comment by romulocintra** [comment]
There documentation for it here https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/@@toStringTag

**Comment by ryzokuken** [comment]
The page is linked on the tiny left sidebar called "related properties" on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl. Should we maybe include it in the main content on the right? Then we could replicated that for each of the constructors?

**Comment by Josh-Cena** [comment]
Hi! Every class page now has a mention of `@@toStringTag`, e.g. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat#instance_properties This can be closed.

**Comment by ben-allen** [comment]
This is complete -- all class pages now have updated `@@toStringTags` (see previous comment from @Josh-Cena)
