### ISSUE TITLE
Figure out documentation strategy for numbering systems

### ISSUE THREAD

**Issue by sffc** [tc39/ecma402-mdn#16]
On https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat, under "Parameters", there is a big list of numbering systems that are accepted.  However, https://github.com/tc39/ecma402/pull/438 extended this list, and Section 2 allows implementations to extend that list further, something that is often done in practice.

Figure out a strategy for documenting numbering systems going forward.

**Comment by romulocintra** [comment]
Similar thing is happening here : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/numberingSystem ,  i would recommend creating a new page with a unified list that can be embed or linked in the MDN docs that way all dependents will in sync

**Comment by romulocintra** [comment]
I just added a link for the NumberSystem List please review if it's ok solution and we can apply whatever is needed.
[Check Here how it looks like](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat)

But there are some values missing there : 

- diak 
- segment

Is corre update them  on the table ? @sffc

**Comment by sffc** [comment]
Looks quite good!

I'm wondering whether we should duplicate the table from the spec in MDN, but I think it's fine.  It's more clear, and whenever we update the spec's table, we will have an action item to update the MDN table.

It's possible that the 402 table lags behind the full list in the Unicode spec.  This is okay.  The 402 table will be updated periodically, just as Frank did last summer.

**Comment by ryzokuken** [comment]
@sffc what's left for this?

**Comment by sffc** [comment]
I think this issue is done!  @romulocintra, please reopen if there is still work remaining.
