### ISSUE TITLE
Document PR #429

### ISSUE THREAD

**Issue by sffc** [tc39/ecma402-mdn#18]
Document https://github.com/tc39/ecma402/pull/429 or decide not to document it.

@jswalden @FrankYFTang

**Comment by jswalden** [comment]
I have (I think) most of this change written locally, just need to verify my changes work in the new world of MDN being roughly Not A Wiki any more.

**Comment by jswalden** [comment]
MDN changes landed, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl now mentions that variant subtags must be unique, including within a "t" extension.  Anyone who wants to should feel free to give the changes in the PR a read-through!

**Comment by sffc** [comment]
Nice!  Thank you!  Let's close this issue then and update the progress tracking spreadsheet.
