### ISSUE TITLE
Intl.Locale Info API

### ISSUE THREAD

**Issue by romulocintra** [tc39/ecma402-mdn#21]
Create Documentation for ** Intl.Locale Info API** 

- [x] Review Readme [documentation and examples](https://github.com/tc39/proposal-intl-locale-info)
- [x] Create/Update MDN Main Docs Page - [Page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale)

**MDN Pages :** 
- PR https://github.com/mdn/content/pull/8985
- [x] Intl.Locale.prototype.weekInfo
- [x] Intl.Locale.prototype.timeZones 
- [x] Intl.Locale.prototype.hourCycles 
- [x] Intl.Locale.prototype.numberingSystems
- [x] Intl.Locale.prototype.textInfo 
- PR https://github.com/mdn/content/pull/8768
 - [x] Intl.Locale.prototype.calendars 
 - [x]  Intl.Locale.prototype.collations

 **Browser compat-data :**  PR https://github.com/mdn/browser-compat-data/pull/12314
- [x] Intl.Locale.prototype.weekInfo
- [x] Intl.Locale.prototype.timeZones
- [x] Intl.Locale.prototype.hourCycles
- [x] Intl.Locale.prototype.numberingSystems
- [x] Intl.Locale.prototype.calendars
- [x] Intl.Locale.prototype.textInfo

**Comment by romulocintra** [comment]
Initial PR preview available at : https://pr5197.content.dev.mdn.mozit.cloud/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale

**Comment by romulocintra** [comment]
It's finally merged closing this one

**Comment by FrankYFTang** [comment]
Missing doc for Intl.Locale.prototype.collations

**Comment by romulocintra** [comment]
> Missing doc for Intl.Locale.prototype.collations

Thanks @FrankYFTang  will take of it ASAP

**Comment by romulocintra** [comment]
@FrankYFTang MDN already ready for review at https://github.com/mdn/content/pull/21357, so when merged this can be closed

**Comment by Josh-Cena** [comment]
Everything is documented, including the more-recent migration to methods, so this can be closed.
