### ISSUE TITLE
Add MDN Documentation for proposed `fractionalSecondDigits`.

### ISSUE THREAD

**Issue by bkardell** [tc39/ecma402-mdn#5]
Add MDN Documentation for proposed `fractionalSecondDigits`.
([Spec](https://github.com/tc39/ecma402/pull/347), [Tests](https://github.com/tc39/test262/pull/2194)

- [x]  Options on [DateTimeFormat Page](https://developer.mozilla.org/enUS/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat)
- [x]  Example on on [DateTimeFormat Page](https://developer.mozilla.org/enUS/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat)
- [x]  Example on on [DateTimeFormat.formatToParts Page](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat/formatToParts)

Question for how we work things on these -- there are a huge number of options that you can provide to things here, and differently interesting combinations.  It seems at a minimum we want to add the above, but do we also want code samples - and do we want them on just this page, or should they be on, for example, `format()` or `formatToParts()` pages?

**Comment by romulocintra** [comment]
Hi, @bkardell I think when you have several examples the texts are long to improve understanding, second option of creating a new page is the best, same as [formatRange](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat/formatRange).

We made similar at this issue to https://github.com/tc39/proposal-intl-DateTimeFormat-formatRange/issues/12

**Comment by bkardell** [comment]
@romulocintra I might be misunderstanding... are you saying that too many examples in a single page doesn't actually probably help (this is my worry)?  Also, WRT creating a new page, that one seems clear as it is its own method.  In this case my worry is about the fact that the options bag has X optional properties (plus defaults) with Y possible values (plus what happens on invalid values) and that this generates, inherently an exceptionally large number of possible uses (this is actually a goal of its design rationale, as I see it) and affect how all of the formatting works.  So, for example, what are your answers to these specific questions:

1. Should the DateTimeFormat page include one or more code examples showing uses of  `fractionalSecondDigits`.  I think no.
2. Should the format() page include one or more examples of this. 
   * If so, why this one? It shouldn't (can't) show all of the possible uses, right?
3. Basically, repeat #2 for all of the properties here which do the formatting.

**Comment by romulocintra** [comment]
Hi @bkardell  sorry for the misunderstanding. 

> 
> 1. Should the DateTimeFormat page include one or more code examples showing uses of  `fractionalSecondDigits`.  I think no.

I think that's no need for a code example for all combinations of properties unless you can integrate with related ones using static examples. I would care about not having a very long page, better split ...

> 2. Should the format() page include one or more examples of this.
>    
>    * If so, why this one? It shouldn't (can't) show all of the possible uses, right?

IMHO we should explain all possible usage and combinations but only create code examples with the more relevant use cases. In the case of creating a unique page for the method, the interactive code sample is ok too.

> 3. Basically, repeat #2 for all of the properties here which do the formatting.

No opinion about that, but probably is the model that scales better...

**Comment by bkardell** [comment]
Ok, I added fractional second digits to the options bag documentation, and to https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat/formatToParts - I'm not sure if there's somewhere else it needs to be, those seem like the most logical bits... ?

The phrasing on that formatToParts page seems a little weird btw, but I'm not sure how to make it better just off the top of my head.

**Comment by bkardell** [comment]
After talking with @littledan I decided to add an example to the `DateTimeFormat` page after all... I think these are in pretty good shape now, I can't see anywhere else this needs something... Anybody have any further thoughts or review?

**Comment by HolgerJeromin** [comment]
I miss a word/table about the browser compatibility.

**Comment by romulocintra** [comment]
@HolgerJeromin where is missing ?  is see it [here](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat/formatToParts#Browser_compatibility).

@bkardell  if all is ok we just need to update the [tracking table](https://github.com/tc39/ecma402/wiki/Proposal-and-PR-Progress-Tracking#ecma-402-prs) replace :hourglass: by  :heavy_check_mark: on fractionalDigits part

**Comment by HolgerJeromin** [comment]
> @HolgerJeromin where is missing ? is see it here.

I thought this issue was about adding `fractionalSecondDigits` to the doc. Reading your link I get the impression that Firefox 51 `formatToParts` returns a `fractionalSecond` part.
[DateTimeFormat#Parameters](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat#Parameters) has an experimental Icon, but no explanation what this means.

**Comment by bkardell** [comment]
I am going to close this as a good first pass, and suggest that we should perhaps have some more general discussions with/about MDN and how to handle things like this - here's why:

This is an early effort and going through some kind of 'not exactly stages' development.  Further, 
it is option in a bag to a constructor of an built-in _is_ standard and supported, but the option isn't.  The option doesn't have some corresponding property or something that I think we can create a page for that we could mark with a big 'experimental' banner, rather most of the impacts are only observed by calling other methods.  Beyond marking a bag item with the experimental icon, I'm not sure what other precedent or MDN technique you could use here to make that clearer inline for one property in the bag.  Because there isn't an implementation landed in stuff tracked and there isn't landed spec prose, and in a few cases on the corners it might still be not 100% clear what 'support' means, I'm not sure we can add a useful entry that would be accepted in https://github.com/mdn/browser-compat-data/edit/master/javascript/builtins/Intl.json.  Then, there are all of the code examples in the various pages... I'm not sure how you would provide them in a good way that helped you correctly determine which things are supported in the format they are in now.  I guess we are lucky the the implementations are somewhat coordinated and not as ragged at they could be.. Like, there's nothing to say that a particular one couldn't ship a constructor which 'supports' the bag item only insofar as it throws range errors on invalid values, but then does nothing practical with it.  I can even kind of imagine someone making a case that this might be good as it would help people catch errors earlier... But, I'm not sure where or how often to call that out - so, I'm going to treat this as a related issue and call this a good first pass...

**Comment by leobalter** [comment]
> Add MDN Documentation for proposed `fractionalSecondDigits`.
> ([Spec](https://github.com/tc39/ecma402/pull/347), [Tests](https://github.com/tc39/test262/pull/2194)
> 
> * [x]   Options on [DateTimeFormat Page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat)
> * [x]   Example on on [DateTimeFormat Page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat)
> * [x]   Example on on [DateTimeFormat.formatToParts Page](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat/formatToParts)
> 
> Question for how we work things on these -- there are a huge number of options that you can provide to things here, and differently interesting combinations. It seems at a minimum we want to add the above, but do we also want code samples - and do we want them on just this page, or should they be on, for example, `format()` or `formatToParts()` pages?

FYI, the links are broken but can be fixed by `r/enUS/en-US/`, I fixed them in this reply comment.
