### ISSUE TITLE
Add dayPeriod option to MDN

### ISSUE THREAD

**Issue by romulocintra** [tc39/ecma402-mdn#6]
Related issue https://github.com/tc39/ecma402/pull/346

**Comment by bkardell** [comment]
- [x] add to options bag documentation
- [x] add exampled on main [DateTimeFormat page](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat$edit)
- [x] add some clarity to output that these values are potentially more than just 'am' or 'pm'

**Comment by romulocintra** [comment]
LGTM closing this one thks @bkardell
