### ISSUE TITLE
Bind Interactive example to DateTimeFormat-formatRangeToParts

### ISSUE THREAD

**Issue by romulocintra** [tc39/ecma402-mdn#7]
https://github.com/mdn/interactive-examples/pull/1444 landed now we need  bind interactive example to the MDN page : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat/formatRangeToParts

**Comment by romulocintra** [comment]
Done

**Comment by sffc** [comment]
Is it intentional that there are nested scrollbars?

![image](https://user-images.githubusercontent.com/1145762/71134081-c833fe00-21b1-11ea-8259-3babfa4a348f.png)

**Comment by romulocintra** [comment]
@sffc  can you provide more details to reproduce(device , resolution) : 

![image](https://user-images.githubusercontent.com/1572026/71135033-bc235d00-2200-11ea-9968-fb6c4dcf9d59.png)


and using iphone XR 

![image](https://user-images.githubusercontent.com/1572026/71135128-10c6d800-2201-11ea-8224-ba699f7330b8.png)

**Comment by sffc** [comment]
Reproduces for me in Chrome and Firefox on Linux at all browser widths.

Can you make the blue box long enough so that you don't have to scroll within the blue box and it just expands down the main page?

**Comment by romulocintra** [comment]
We don’t have control on how this is styled, there are different sizes of interactive examples to accommodate the code. But it looks like an issue in the MDN. I will have a look at to figure out the best way to reproduce and solve it.

**Comment by romulocintra** [comment]
Not able to reproduce MDN already changed a lot in styling etc since then and those views are stale
