### ISSUE TITLE
Normative: Add calendar and numberingSystem options

### ISSUE THREAD

**Issue by romulocintra** [tc39/ecma402-mdn#8]
Missing MDN documentation

**Comment by bkardell** [comment]
Actually, I began this before we created this repository - I think [this](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat$revision/1592648) is the first commit.  As you can see in the [DateTimeFormat](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat) page there are docs on the options bag, as well as a separate set of examples under 'using options'.   Are there other places that there should be more?

**Comment by romulocintra** [comment]
LGTM  , Just updated the tracking table and closing the issue https://github.com/tc39/ecma402/wiki/Proposal-and-PR-Progress-Tracking
